#Layout detection models
logics_parsing:
  checkpoint: ""
  gpu_ids: [4,5,6,7]

indic-dlp:
  checkpoint: "/fsxvision/srihari.bandarupalli/layout-detection/checkpoints/doclayout_yolo_indicdlp.pt"
  gpu_ids: [0,1,2,3]

doclaynet:
  checkpoint: "/fsxvision/srihari.bandarupalli/layout-detection/checkpoints/doclayout_yolo_docstructbench_imgsz1024.pt"
  gpu_ids: [4,5,6,7]